name: Build & deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.10]

    steps:
      - uses: actions/checkout@v4
      - name: 💻 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🏗️ Build static website
        run: npm run build:gh

      - name: 🚀 Upload artifact 
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public

      - name: 🏁 Deploy to GitHub Pages
        id: gh-pages
        uses: actions/deploy-pages@v4
